name: Continuous Integration and Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Build Project
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DTT_LOGGER_BUILD_TESTING=ON
        cmake --build build --parallel

    - name: Run Tests
      run: |
        ctest -V --test-dir build
